In [1]:
import pandas as pd
import numpy as np

In [2]:
results = pd.read_csv("../data/raw/results.csv")

In [3]:
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [4]:
results.shape

(49477, 9)

In [5]:
results.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

In [6]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  object
 1   home_team   49477 non-null  object
 2   away_team   49477 non-null  object
 3   home_score  49433 non-null  float64
 4   away_score  49433 non-null  float64
 5   tournament  49477 non-null  object
 6   city        49477 non-null  object
 7   country     49477 non-null  object
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [7]:
results["date"] = pd.to_datetime(results["date"])

In [8]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  datetime64[ns]
 1   home_team   49477 non-null  object
 2   away_team   49477 non-null  object
 3   home_score  49433 non-null  float64
 4   away_score  49433 non-null  float64
 5   tournament  49477 non-null  object
 6   city        49477 non-null  object
 7   country     49477 non-null  object
 8   neutral     49477 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(5)
memory usage: 3.1+ MB

In [9]:
def get_result(row):
    if row["home_score"] > row["away_score"]:
        return "Home Win"
    elif row["home_score"] < row["away_score"]:
        return "Away Win"
    else:
        return "Draw"

In [10]:
results["result"] = results.apply(get_result, axis=1)

In [11]:
results[["home_team", "away_team", "home_score", "away_score", "result"]].head()

  home_team away_team  home_score  away_score    result
0  Scotland   England         0.0         0.0      Draw
1   England  Scotland         4.0         2.0  Home Win
2  Scotland   England         2.0         1.0  Home Win
3   England  Scotland         2.0         2.0      Draw
4  Scotland   England         3.0         0.0  Home Win

In [13]:
result_map = {
    "Home Win": 1,
    "Draw": 0,
    "Away Win": -1
}

results["result_label"] = results["result"].map(result_map)

In [14]:
results[["home_team", "away_team", "home_score", "away_score", "result", "result_label"]].head()

  home_team away_team  home_score  away_score    result  result_label
0  Scotland   England         0.0         0.0      Draw             0
1   England  Scotland         4.0         2.0  Home Win             1
2  Scotland   England         2.0         1.0  Home Win             1
3   England  Scotland         2.0         2.0      Draw             0
4  Scotland   England         3.0         0.0  Home Win             1

In [15]:
results["result"].value_counts()

result
Home Win    24227
Away Win    13963
Draw        11287
Name: count, dtype: int64

In [16]:
results["result"].value_counts(normalize=True)

result
Home Win    0.489662
Away Win    0.282212
Draw        0.228126
Name: proportion, dtype: float64

In [17]:
results.to_csv("../data/processed/cleaned_results.csv", index=False)